// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ZHuWpo3Rm2ZFVHCv-yF_aRyWis2uGKc',
    appId: '1:171552153953:web:3cd5ee1006608add832520',
    messagingSenderId: '171552153953',
    projectId: 'apu-rideshare',
    authDomain: 'apu-rideshare.firebaseapp.com',
    storageBucket: 'apu-rideshare.appspot.com',
    measurementId: 'G-WHK73CXH3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUVQAX7SpwixexK7m7I4rqBAI1e3aAVHU',
    appId: '1:171552153953:android:f178ba74677b0ef6832520',
    messagingSenderId: '171552153953',
    projectId: 'apu-rideshare',
    storageBucket: 'apu-rideshare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBED2KtNL9_XG4N3x3PUebEChDfwphHHdU',
    appId: '1:171552153953:ios:3a33aefac6c01c15832520',
    messagingSenderId: '171552153953',
    projectId: 'apu-rideshare',
    storageBucket: 'apu-rideshare.appspot.com',
    iosClientId:
        '171552153953-jfgp8414omsqrdo1k3b54ujekonqv5d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.apuRideshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBED2KtNL9_XG4N3x3PUebEChDfwphHHdU',
    appId: '1:171552153953:ios:3a33aefac6c01c15832520',
    messagingSenderId: '171552153953',
    projectId: 'apu-rideshare',
    storageBucket: 'apu-rideshare.appspot.com',
    iosClientId:
        '171552153953-jfgp8414omsqrdo1k3b54ujekonqv5d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.apuRideshare',
  );
}
