name: build-apk
on:
  push:
    branches:
      - master
      
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3.1.2
        with:
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5
